export const LOAD_DATA_INITIATION = 'PROFILECONTAINER/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS = 'PROFILECONTAINER/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'PROFILECONTAINER/LOAD_DATA_FAILURE';
