export const LOAD_DATA_INITIATION = 'REPOSITORYDETAILCONTAINER/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS = 'REPOSITORYDETAILCONTAINER/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'REPOSITORYDETAILCONTAINER/LOAD_DATA_FAILURE';
