export const LOAD_DATA_INITIATION = 'STARSCONTAINER/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS = 'STARSCONTAINER/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'STARSCONTAINER/LOAD_DATA_FAILURE';
